#pragma once

typedef enum status_e {
	SUCCESS = 0,
	UNINITIALIZED,
    INVALID_PARAMETERS,
	
	// shell status
	SHELL__FAILED_ALLOCATING_BUFFER_FOR_COMMAND,
	SHELL__FAILED_READING_LINE,
    SHELL__INPUT_TOO_LONG,

	//comms status
	COMMS__INVALID_COMMAND,
    COMMS__FAILED_SENDING_MESSAGE,
    COMMS__FAILED_CREATING_SERVER_SOCKET,
    COMMS__FAILED_BINDING_ADDRESS,
    COMMS__FAILED_LISTEN,
    COMMS__FAILED_ACCEPTING_NEW_CLIENT,
    COMMS__FAILED_ALLOCATING_BUFFER_FOR_RECIEVING_MESSAGE,
    COMMS__FAILED_RECEIVING_MESSAGE_FROM_CLIENT,
    COMMS__INCORRECT_MAGIC,

    // db
    DB__FAILED_OPENING_DB_FILE,
    DB__FAILED_ALLOCATING_DB,
    DB__FAILED_FITTING_DB,

    // pool
    POOL__FAILED_CREATING_WORKER,
    POOL__FAILED_ALLOCATING_WORKERS,
    POOL__FAILED_DESTROYING_POOL,
    POOL__FAILED_INITIALIZING_POOL,

    //queue
    QUEUE__FAILED_INITIALIZING_QUEUE,
    QUEUE__FAILED_INITIALZING_MUTEX,
    QUEUE__FAILED_ALLOCATING_NEW_NODE,
    QUEUE__POPING_FROM_EMPTY_QUEUE,
    QUEUE__FAILED_INITIALIZING_COND,
    QUEUE__FAILED_LOCKING_MUTEX,

    // grade server
    GRADE_SERVER__FAILED_SETTING_SIGINT_HANDLER,
} status_t;
