#pragma once

typedef enum status_e {
	SUCCESS = 0,
	UNINITIALIZED,
    INVALID_PARAMETERS,
	
	// shell status
	SHELL__FAILED_ALLOCATING_BUFFER_FOR_COMMAND,
	SHELL__FAILED_READING_LINE,
    SHELL__INPUT_TOO_LONG,

	//comms status
	COMMS__INVALID_COMMAND,
    COMMS__FAILED_SENDING_MESSAGE,

    // db
    DB__FAILED_OPENING_DB_FILE,
    DB__FAILED_ALLOCATING_DB,
    DB__FAILED_FITTING_DB,
} status_t;
